version: "3.7"
services:
  app:
    image: adrum/wireguard-ui
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    network_mode: "host"
    volumes:
      - ./data:/data
      - /lib/modules:/lib/modules
    environment:
      - WIREGUARD_UI_LISTEN_ADDRESS=:8080
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_WG_ENDPOINT=your-endpoint-address:51820
      - WIREGUARD_UI_WG_KEEP_ALIVE=25
      - WIREGUARD_UI_CLIENT_IP_RANGE=192.168.10.0/24
     # - WIREGUARD_UI_WG_DNS=192.168.10.0
      - WIREGUARD_UI_NAT=true
      - WIREGUARD_UI_NAT_DEVICE=eth0
    restart: always
